

                      
  [RuntimeException]  
  Second exception    
                      




                      
  [RuntimeException]  
  First exception     
                      


foo3:bar


